blank_issues_enabled: false
contact_links:
  - name: ğŸ› Bug Report
    url: https://github.com/sayfer-io/Snapper/issues/new?template=bug_report.yml
    about: Report a problem, bug, or unexpected behaviour in the project.
  - name: ğŸŒŸ Feature Request
    url: https://github.com/sayfer-io/Snapper/issues/new?template=feature_request.yml
    about: Suggest a new feature or improvement for the project.
